services:

  nginx-pm:
    container_name: nginx-pm
    image: jc21/nginx-proxy-manager:latest
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    ports:
      - ${PORT_NGINX_IO}:80
      - ${PORT_NGINX_HTTP}:81
      - ${PORT_NGINX_HTTPS}:443
    volumes: 
      - ${CONFIG_NGINX}/data:/data
      - ${CONFIG_NGINX}/ssl:/etc/letsencrypt
    restart: always