services:

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    depends_on:
      - prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - DOCKER_MODS=${PARK}:radarr
      - TP_THEME=${THEME}
      - TP_COMMUNITY_THEME=${THEME_COMMUNITY}
    ports:
      - ${PORT_RADARR}:${PORT_RADARR}
    volumes:
      - ${CONFIG_RADARR}:/config
      - ${MEDIA_MOVIE}:/movies
      - ${MEDIA_DOWNLOADS}:/downloads
    restart: unless-stopped