services:

  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - BASE_URL=https://${IP_DOMAIN}
      - ALLOW_SIGNUP=false
    volumes:
      - ${CONFIG_MEALIE}:/app/data
    ports:
      - ${PORT_MEALIE}:9000
    deploy:
      resources:
        limits:
          memory: 1000M