services:

  sillytavern:
    build: ..
    container_name: sillytavern
    hostname: sillytavern
    network_mode: host
    image: ghcr.io/sillytavern/sillytavern:latest
    environment:
      - NODE_ENV=production
      - FORCE_COLOR=1
    ports:
      - "9000:9000"
    volumes:
      - "${CONFIG}/sillytavern/config:/home/node/app/config"
      - "${CONFIG}/sillytavern/data:/home/node/app/data"
      - "${CONFIG}/sillytavern/plugins:/home/node/app/plugins"
      - "${CONFIG}/sillytavern/extensions:/home/node/app/public/scripts/extensions/third-party"
    restart: unless-stopped