services:

  calibre-web:
    container_name: calibre-web
    image: lscr.io/linuxserver/calibre-web:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - DOCKER_MODS=${PARK}:calibreweb
      - TP_THEME=${THEME}
      - TP_COMMUNITY_THEME=${THEME_COMMUNITY}
    ports:
      - ${PORT_CALIBRE}:8083
    volumes:
      - ${CONFIG_CALIBRE}/web:/config
      - ${MEDIA_BOOKS}:/books
    restart: unless-stopped