services:

  deunhealth:
    container_name: deunhealth
    image: qmcgaw/deunhealth:latest
    build: .
    environment:
      - TZ=${TIME}
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - LOG_LEVEL=info
    volumes:
      - ${SOCK}:${SOCK}
    restart: always

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    command: --cleanup=true --include-restarting=true --include-stopped=true --interval=86400
    volumes:
      - ${SOCK}:${SOCK}
    restart: always