- Bookmarks:
  - Proton Mail:
    - abbr: "PM"
      href: "https://mail.proton.me/u/1/inbox"
  - YouTube:
    - abbr: "Y"
      href: "https://www.youtube.com/feed/subscriptions"
  - YouTube Music:
    - abbr: "YM"
      href: "https://music.youtube.com/library/playlists"
  - Reddit:
    - abbr: "R"
      href: "https://www.reddit.com/?feed=home"
  - GitHub:
    - abbr: "GH"
      href: "https://www.github.com/Furglitch"