- Media:
    - Plex:
        icon: plex.png
        url: http://192.168.X.X:PORT/
        href: http://192.168.X.X:PORT/
        key: API_KEY
        description: "Plex Media Server"
        server: localhost
        container: plex
        widgets:
        - type: tautulli
          url: http://192.168.X.X:PORT/
          key: API_KEY
    #- Jellyfin:
    #    icon: jellyfin.png
    #    url: http://192.168.X.X:PORT/
    #    href: http://192.168.X.X:PORT/
    #    key: API_KEY
    #    description: "Jellyfin Media Server"
    #    server: localhost
    #    container: jellyfin
    - "AudioBookshelf":
        icon: audiobookshelf.png
        href: http://192.168.X.X:PORT/
        siteMonitor: http://192.168.X.X:PORT/
        description: "Books and Audiobooks"

- Servarr:
    - Sonarr:
        icon: sonarr.png
        href: http://192.168.X.X:PORT/
        widgets:
        - type: sonarr
          url: http://192.168.X.X:PORT/
          key: API_KEY
    - Radarr:
        icon: radarr.png
        href: http://192.168.X.X:PORT/
        widgets:
        - type: radarr
          url: http://192.168.X.X:PORT/
          key: API_KEY
    - Bazarr:
        icon: bazarr.png
        href: http://192.168.X.X:PORT/
        widgets:
        - type: bazarr
          url: http://192.168.X.X:PORT/
          key: API_KEY
    - Prowlarr:
        icon: prowlarr.png
        href: http://192.168.X.X:PORT/
        widgets:
        - type: prowlarr
          url: http://192.168.X.X:PORT/
          key: API_KEY

- Download:
    - "SABnzbd":
        icon: sabnzbd.png
        href: http://192.168.X.X:PORT/
        widgets:
        - type: sabnzbd
          url: http://192.168.X.X:PORT/
          key: API_KEY
    - "qBittorrent":
        icon: qbittorrent.png
        href: http://192.168.X.X:PORT/
        widgets:
        - type: qbittorrent
          url: http://192.168.X.X:PORT/
          username: admin
          password: PASSWORD

- "Web":
    - "VaultWarden":
        icon: vaultwarden.png
        href: http://192.168.X.X:PORT/
        siteMonitor: http://192.168.X.X:PORT/
        description: "Password Manager"
    - "Nextcloud":
        icon: nextcloud.png
        href: http://192.168.X.X:PORT/
        siteMonitor: http://192.168.X.X:PORT/
        description: "Cloud Storage"
    - "Mealie":
        icon: mealie.png
        href: http://192.168.X.X:PORT/
        siteMonitor: http://192.168.X.X:PORT/
        description: "Meal Planning"
    - "SillyTavern":
        icon: https://sillytavern.app/img/logo.png
        href: http://192.168.X.X:PORT/
        siteMonitor: http://192.168.X.X:PORT/
        description: "AI Chat Client"
    - "MediaWiki":
        icon: mediawiki.png
        href: http://192.168.X.X:PORT/
        siteMonitor: http://192.168.X.X:PORT/
        description: "Wiki"