background: 
  image: "https://raw.githubusercontent.com/orangci/walls-catppuccin-mocha/master/pixel-galaxy.png"
  blur: sm
cardBlur: md

theme: dark
color: cyan

headerStyle: boxed
layout:
  Media:
    style: row
    columns: 1
  Servarr:
    style: row
    columns: 2
  Download:
    style: row
    columns: 2

hideVersion: true
disableUpdateCheck: true