services:

  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    ports:
      - ${PORT_VAULTWARDEN}:80
    volumes: 
      - ${CONFIG_VAULTWARDEN}:/config
      - ${CONFIG_VAULTWARDEN}/data:/data
    restart: always