services:

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    depends_on:
      - prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - DOCKER_MODS=${PARK}:sonarr
      - TP_THEME=${THEME}
      - TP_COMMUNITY_THEME=${THEME_COMMUNITY}
    ports:
      - ${PORT_SONARR}:${PORT_SONARR}
    volumes:
      - ${CONFIG_SONARR}:/config
      - ${MEDIA_TV}:/tv
      - ${MEDIA_DOWNLOADS}:/downloads
    restart: unless-stopped