services:

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    depends_on:
      - prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - DOCKER_MODS=${PARK}:sonarr
      - TP_THEME=${THEME}
      - TP_COMMUNITY_THEME=${THEME_COMMUNITY}
    ports:
      - ${PORT_SONARR}:${PORT_SONARR}
    volumes:
      - ${CONFIG_SONARR}:/config
      - ${MEDIA_TV}:/tv
      - ${MEDIA_DOWNLOADS}:/downloads
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    depends_on:
      - prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - DOCKER_MODS=${PARK}:radarr
      - TP_THEME=${THEME}
      - TP_COMMUNITY_THEME=${THEME_COMMUNITY}
    ports:
      - ${PORT_RADARR}:${PORT_RADARR}
    volumes:
      - ${CONFIG_RADARR}:/config
      - ${MEDIA_MOVIE}:/movies
      - ${MEDIA_DOWNLOADS}:/downloads
    restart: unless-stopped
  
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - DOCKER_MODS=${PARK}:prowlarr
      - TP_THEME=${THEME}
      - TP_COMMUNITY_THEME=${THEME_COMMUNITY}
    ports:
      - ${PORT_PROWLARR}:${PORT_PROWLARR}
    volumes:
      - ${CONFIG_PROWLARR}:/config
      - ${MEDIA_DOWNLOADS}:/downloads
    restart: unless-stopped

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - LOG_LEVEL=info
    ports:
      - ${PORT_FLARESOLVER}:8191
    volumes:
      - ${CONFIG_FLARESOLVER}:/config
    restart: unless-stopped