services:

  sonarr:
    container_name: sonarr
    image: lscr.io/linuxserver/sonarr:latest
    depends_on:
      - prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TIME}
      - DOCKER_MODS=${PARK}:sonarr
      - TP_THEME=${THEME}
    ports:
      - 32402:8989
    volumes:
      - ${CONFIG}/sonarr:/config
      - ${SHARE}:/share
      - ${SHARE}/downloads:/downloads
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:latest
    depends_on:
      - prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TIME}
      - DOCKER_MODS=${PARK}:radarr
      - TP_THEME=${THEME}
    ports:
      - 32403:7878
    volumes:
      - ${CONFIG}/radarr:/config
      - ${SHARE}:/share
      - ${SHARE}/downloads:/downloads
    restart: unless-stopped
  
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TIME}
      - DOCKER_MODS=${PARK}:prowlarr
      - TP_THEME=${THEME}
    ports:
      - 32404:9696
    volumes:
      - ${CONFIG}/prowlarr:/config
      - ${SHARE}:/share
      - ${SHARE}/downloads:/downloads
    restart: unless-stopped

  flaresolverr:
    container_name: flaresolverr
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TIME}
      - LOG_LEVEL=info
    ports:
      - 32405:8191
    volumes:
      - ${CONFIG}/flaresolverr:/config
    restart: unless-stopped