services:

  sillytavern:
    build: ..
    container_name: sillytavern
    hostname: sillytavern
    image: ghcr.io/sillytavern/sillytavern:latest
    environment:
      - NODE_ENV=production
      - FORCE_COLOR=1
    ports:
      - ${PORT_SILLYTAVERN}:8000
    volumes:
      - ${CONFIG_SILLYTAVERN}/config:/home/node/app/config
      - ${CONFIG_SILLYTAVERN}/data:/home/node/app/data
      - ${CONFIG_SILLYTAVERN}/plugins:/home/node/app/plugins
      - ${CONFIG_SILLYTAVERN}/extensions:/home/node/app/public/scripts/extensions/third-party
    restart: unless-stopped