services:

  sabnzbd:
    container_name: sabnzbd
    image: lscr.io/linuxserver/sabnzbd:latest
    network_mode: 'service:gluetun'
    labels:
      - "deunhealth.restart.on.unhealthy=true"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - DOCKER_MODS=${PARK}:sabnzbd
      - TP_THEME=${THEME}
      - TP_COMMUNITY_THEME=${THEME_COMMUNITY}
    volumes:
      - ${CONFIG_SABNZBD}:/config
      - ${DOWNLOADS_SABNZBD}:/downloads/usenet
      - ${DOWNLOADS_SABNZBD_INCOMPLETE}:/downloads/usenet/incomplete
    restart: unless-stopped