services:

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - DOCKER_MODS=${PARK}:bazarr
      - TP_THEME=${THEME}
      - TP_COMMUNITY_THEME=${THEME_COMMUNITY}
    ports:
      - ${PORT_BAZARR}:${PORT_BAZARR}
    volumes:
      - ${CONFIG_BAZARR}:/config
      - ${MEDIA_MOVIE}:/movies
      - ${MEDIA_TV}:/tv
    restart: unless-stopped