version: '3.8'
services:
  deunhealth:
    container_name: deunhealth
    image: qmcgaw/deunhealth:latest
    build: .
    environment:
      - TZ=${TZ}
      - HEALTH_SERVER_ADDRESS=127.0.0.1:9999
      - LOG_LEVEL=info
    volumes:
      - ${DOCKER_SOCK}:${DOCKER_SOCK}
    restart: always

  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=${GLUETUN_PROVIDER}
      - VPN_TYPE=${GLUETUN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${GLUETUN_KEY}
      - BLOCK_MALICIOUS=off
    ports:
      - ${PORT_SABNZBD}:${PORT_SABNZBD}
      - ${PORT_QBITTORRENT_UI}:${PORT_QBITTORRENT_UI}
      - ${PORT_QBITTORRENT_IO}:${PORT_QBITTORRENT_IO}
    volumes:
      - ${CONFIG_GLUETUN}:/gluetun
    restart: always

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower:latest
    command: --cleanup=true --include-restarting=true --include-stopped=true --interval=86400
    volumes:
      - ${DOCKER_SOCK}:${DOCKER_SOCK}
    restart: always
