services:

  glance:
    container_name: glance
    image: glanceapp/glance:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TIME}
    ports:
      - 8095:8080
    volumes:
      - ${CONFIG}/glance:/app/config
    restart: unless-stopped