services:

  glance:
    container_name: glance
    image: glanceapp/glance:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    ports:
      - ${PORT_GLANCE}:8080
    volumes:
      - ${CONFIG_GLANCE}:/app/config
    restart: unless-stopped