services:

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
    ports:
      - ${PORT_AUDIOBOOKSHELF}:80
    volumes:
      - ${CONFIG_AUDIOBOOKSHELF}/books:/books
      - ${CONFIG_AUDIOBOOKSHELF}/podcasts:/podcasts
      - ${CONFIG_AUDIOBOOKSHELF}/config:/config
      - ${CONFIG_AUDIOBOOKSHELF}/metadata:/metadata