services:
  
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    environment:
      - VERSION=docker
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - DOCKER_MODS=${PARK}:plex
      - TP_THEME=${THEME}
      - TP_COMMUNITY_THEME=${THEME_COMMUNITY}
    ports:
      - ${PORT_PLEX}:32400
    volumes:
      - ${CONFIG_PLEX}:/config/Library/Application Support/Plex Media Server
      - ${MEDIA_MOVIE}:/movies
      - ${MEDIA_TV}:/tv
      - ${MEDIA_MUSIC}:/music
    restart: unless-stopped