services:
  
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    environment:
      - VERSION=docker
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - DOCKER_MODS=${PARK}:plex
      - TP_THEME=${THEME}
    ports:
      - ${PORT_PLEX}:32400
    volumes:
      - ${CONFIG_PLEX}:/config
      - ${MEDIA_MOVIE}:/movies
      - ${MEDIA_TV}:/tv
    restart: unless-stopped

  ombi:
    container_name: ombi
    image: lscr.io/linuxserver/ombi:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - DOCKER_MODS=${PARK}:ombi
      - TP_THEME=${THEME}
    ports:
      - ${PORT_OMBI}:3579
    volumes:
      - ${CONFIG_OMBI}:/config
    restart: unless-stopped

  kometa:
    container_name: kometa
    image: kometateam/kometa:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - KOMETA_TIME=00:00,06:00,12:00,18:00
      - KOMETA_CONFIG=/config/config.yml
      - KOMETA_RUN=True
    volumes:
      - ${CONFIG_KOMETA}:/config
    restart: unless-stopped