services:
  
  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    network_mode: host
    environment:
      - VERSION=docker
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - DOCKER_MODS=${PARK}:plex
      - TP_THEME=${THEME}
      - TP_COMMUNITY_THEME=${THEME_COMMUNITY}
    ports:
      - ${PORT_PLEX}:32400
    volumes:
      - ${CONFIG_PLEX}:/config/Library/Application Support/Plex Media Server
      - ${MEDIA_MOVIE}:/movies
      - ${MEDIA_TV}:/tv
      - ${MEDIA_MUSIC}:/music
    restart: unless-stopped

  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    environment:
      - TZ=${TZ}
      - LOG_LEVEL=info
    ports:
      - ${PORT_JELLYSEERR}:5055
    volumes:
      - ${CONFIG_JELLYSEERR}:/config
    restart: unless-stopped

  kometa:
    container_name: kometa
    image: kometateam/kometa:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - KOMETA_TIME=00:00,06:00,12:00,18:00
      - KOMETA_CONFIG=/config/config.yml
      - KOMETA_RUN=True
    volumes:
      - ${CONFIG_KOMETA}:/config
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "10m"
    restart: unless-stopped
  
  tautulli:
    container_name: tautulli
    image: lscr.io/linuxserver/tautulli:latest
    environment:
      - VERSION=docker
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - DOCKER_MODS=${PARK}:tautulli
      - TP_THEME=${THEME}
      - TP_COMMUNITY_THEME=${THEME_COMMUNITY}
    ports:
      - ${PORT_TAUTULLI}:${PORT_TAUTULLI}
    volumes:
      - ${CONFIG_TAUTULLI}:/config
    restart: unless-stopped