services:

  mediawiki:
    container_name: mediawiki
    image: ubcctlt/mediawiki
    ports:
      - ${PORT_MEDIAWIKI}:80
    environment:
      - MEDIAWIKI_SITE_SERVER=http://${IP_LOCAL}:${PORT_MEDIAWIKI}
      - RESTBASE_URL=http://nodeservices:7231
      - MEDIAWIKI_SHARED=/data 
    volumes:
      - ${CONFIG_MEDIAWIKI}/data/:/data/
      - ${CONFIG_MEDIAWIKI}/LocalSettings.php:/var/www/html/LocalSettings.php
    links:
      - mediawiki-db
    restart: unless-stopped

  mediawiki-db:
    container_name: mediawiki-db
    image: mariadb
    environment:
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_PASSWORD}
    volumes:
      - ${CONFIG_MEDIAWIKI}/db:/var/lib/mysql
    restart: unless-stopped

  mediawiki-node:
    container_name: mediawiki-node
    image: ubcctlt/mediawiki-node-services
    environment:
      - MEDIAWIKI_API_URL=http://mediawiki/api.php
      - MEDIAWIKI_REST_URL=http://mediawiki/rest.php
      - LOG_LEVEL=debug
    volumes:
      - ${CONFIG_MEDIAWIKI}/node:/data