services:

  mediawiki:
    container_name: mediawiki
    image: mediawiki
    ports:
      - ${PORT_MEDIAWIKI}:80
    environment:
      - MEDIAWIKI_DB_TYPE=mysql
      - MEDIAWIKI_DB_HOST=mediawiki-db
      - MEDIAWIKI_DB_NAME=mediawiki
      - MEDIAWIKI_DB_USER=${MYSQL_USER}
      - MEDIAWIKI_DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${CONFIG_MEDIAWIKI}/images:/var/www/html/images
      #- ${CONFIG_MEDIAWIKI}/LocalSettings.php:/var/www/html/LocalSettings.php
    depends_on:
      - mediawiki-db
    restart: unless-stopped

  mediawiki-db:
    container_name: mediawiki-db
    image: mariadb
    environment:
      - MYSQL_DATABASE=mediawiki
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=${MYSQL_RANDOM_PASSWORD}
    volumes:
      - ${CONFIG_MEDIAWIKI}/db:/var/lib/mysql
    restart: unless-stopped
