playlists:

  Blade Runner (Chronological):
    libraries: Movies, TV Shows
    sync_to_users: all
    url_poster: https://seeklogo.com/images/B/blade-runner-unicorn-logo-18FA59EA1D-seeklogo.com.png
    trakt_list: https://trakt.tv/users/purokushi/lists/blade-runnerverse
    summary: Blade Runner in Chronological Order

  Breaking Bad (Chronological):
    libraries: Movies, TV Shows
    sync_to_users: all
    url_poster: https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/763e4a4f-0453-48cd-96ef-d2aba6b7d98d/dcc5qrb-37937095-c6f2-424e-9f3b-05a55001242d.png/v1/fill/w_894,h_894,q_70,strp/breaking_bad_logo_wallpaper_by_robinle_dcc5qrb-pre.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9NTAwMCIsInBhdGgiOiJcL2ZcLzc2M2U0YTRmLTA0NTMtNDhjZC05NmVmLWQyYWJhNmI3ZDk4ZFwvZGNjNXFyYi0zNzkzNzA5NS1jNmYyLTQyNGUtOWYzYi0wNWE1NTAwMTI0MmQucG5nIiwid2lkdGgiOiI8PTUwMDAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.A0FxwVrWYWKnS7qH6odPDnUdq4mT71DPfFUlSfNmYBk
    trakt_list: https://trakt.tv/users/vargajoe/lists/breaking-bad-chronology
    summary: Breaking Bad in Chronological Order

  DC Snyderverse (Chronological):
    libraries: Movies, TV Shows
    sync_to_users: all
    url_poster: https://pbs.twimg.com/profile_images/1030705567944208384/d5rh9l1o_400x400.jpg
    trakt_list: https://trakt.tv/users/oblogdamari/lists/dceu-dc-extended-universe
    summary: DCEU in Chronological Order

  Fast and Furious (Chronological):
    libraries: Movies
    sync_to_users: all
    url_poster: https://pbs.twimg.com/profile_images/1788359324307537920/pgT8qjpl_400x400.jpg
    trakt_list: https://trakt.tv/lists/official/the-fast-and-the-furious-collection
    summary: Fast and Furious in Chronological Order

  James Bond (Chronological):
    libraries: Movies
    sync_to_users: all
    url_poster: https://img.asmedia.epimg.net/resizer/v2/MJMN3TW65BIZRG7XLNQIZR6Q5E.jpg?auth=018552aee32083489b7784d62dd87c9604470f31efce06b353e36b963353e49f&width=1200&height=1200&smart=true
    trakt_list: https://trakt.tv/users/amarantha/lists/james-bond
    summary: James Bond in Chronological Order

  Kingsman (Chronological):
    libraries: Movies
    sync_to_users: all
    url_poster: https://pbs.twimg.com/profile_images/1463221870644248578/xZXxHVZO_400x400.jpg
    trakt_list: https://trakt.tv/lists/official/kingsman-collection
    summary: Kingsman in Chronological Order

  Marvel Cinematic Universe (Chronological):
    libraries: Movies, TV Shows
    sync_to_users: all
    url_poster: https://d.newsweek.com/en/full/1439947/marvels-avengers-square-enix-e3-2019-gameplay-co-op.jpg?w=1600&h=1600&q=88&f=c5000aab0c3da427f12911728449bd29
    trakt_list: https://trakt.tv/users/donxy/lists/marvel-cinematic-universe
    summary: Marvel Cinematic Universe in Chronological Order

  Middle Earth (Chronological):
    libraries: Movies, TV Shows
    sync_to_users: all
    url_poster: https://static.wikia.nocookie.net/lotrminecraftmod/images/0/0e/Lord_of_the_Rings.jpg/revision/latest?cb=20190126091156
    trakt_list: https://trakt.tv/users/oya-kesh/lists/middle-earth
    summary: Middle Earth collection in Chronological Order

  MonsterVerse (Chronological):
    libraries: Movies, TV Shows
    sync_to_users: all
    url_poster: https://pbs.twimg.com/profile_images/1725558079541096448/epMIks1Q_400x400.jpg
    trakt_list: https://trakt.tv/users/folion/lists/monsterverse
    summary: MonsterVerse in Chronological Order

  My Little Pony (Chronological):
    libraries: Movies, TV Shows
    sync_to_users: all
    url_poster: https://i.ibb.co/HxJw7S2/Untitled.png
    trakt_list: https://trakt.tv/users/furglitch/lists/my-little-pony-chronological
    summary: My Little Pony in Chronological Order

  Pokemon (Chronological):
    libraries: Movies, TV Shows
    sync_to_users: all
    url_poster: https://www.webwise.ie/wp-content/uploads/2016/07/pokemon-go.png
    trakt_list: https://trakt.tv/users/seriouspain/lists/pokemon
    summary: Pokemon in Chronological Order

  Star Trek (Chronological):
    libraries: Movies, TV Shows
    sync_to_users: all
    url_poster: https://image.api.playstation.com/gs2-sec/appkgo/prod/CUSA05761_00/4/i_f32effd1248cce45a393b93630cb707b0d2b5af8607bc3a2e15f5b8efb4f07ee/i/icon0.png
    trakt_list: https://trakt.tv/users/silvol/lists/star-trek
    summary: Star Trek in Chronological Order

  Star Wars (Chronological):
    libraries: Movies, TV Shows
    sync_to_users: all
    url_poster: https://4vector.com/i/free-vector-star-wars-1_063193_star-wars-1.png
    trakt_list: https://trakt.tv/users/silvol/lists/star-wars
    summary: Star Wars in Chronological Order

  Stargate (Chronological):
    libraries: Movies, TV Shows
    sync_to_users: all
    url_poster: https://www.sexyhackers.com/cdn/shop/products/Stargate_Logo_Square_0af4215a-77dc-4fb9-bbc2-f9ff7ebaff00_1200x1200.jpg?v=1560278637
    trakt_list: https://trakt.tv/users/stziza/lists/stargate-watching-order
    summary: Stargate in Chronological Order

  X-Men (Chronological):
    libraries: Movies, TV Shows
    sync_to_users: all
    url_poster: https://i.pinimg.com/originals/6f/2c/57/6f2c57ced05757e1a24cd6cd0705160a.jpg
    trakt_list: https://trakt.tv/users/donxy/lists/x-men-universe
    summary: X-Men in Chronological Order
