services:
  
  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - DOCKER_MODS=${PARK}:prowlarr
      - TP_THEME=${THEME}
      - TP_COMMUNITY_THEME=${THEME_COMMUNITY}
    ports:
      - ${PORT_PROWLARR}:${PORT_PROWLARR}
    volumes:
      - ${CONFIG_PROWLARR}:/config
      - ${MEDIA_DOWNLOADS}:/downloads
    restart: unless-stopped