services:

  nextcloud:
    container_name: nextcloud
    image: lscr.io/linuxserver/nextcloud:latest
    environment: 
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - TZ=${TZ}
      - VIRTUAL_HOST=http://192.168.X.X:${PORT_NEXTCLOUD}
      - LETSENCRYPT_HOST=http://192.168.X.X:${PORT_NEXTCLOUD}
    ports:
      - ${PORT_NEXTCLOUD}:443
    volumes: 
      - '${CONFIG_NEXTCLOUD}/config:/config'
      - '${CONFIG_NEXTCLOUD}/data:/data'
      - '${CLOUD_NEXTCLOUD}:/share'
    restart: always